variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - lint
  - build

# Login for git
before_script:
  - echo -e "machine git.coinninja.net\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > $HOME/.netrc

test:
  stage: test
  script:
    - go test ./...

golangci-lint:
  stage: lint
  image: registry.coinninja.net/engineering/go-ci:latest
  script:
    - golangci-lint run

.build: &build
  allow_failure: false
  script:
    - export GOPATH=$PWD/gopath
    - export GO111MODULE=off
    - mkdir -p gopath/src/git.coinninja.net/engineering
    - ln -s $PWD gopath/src/git.coinninja.net/engineering/cnlib
    - cd gopath/src/git.coinninja.net/engineering/cnlib
    - go get golang.org/x/mobile/cmd/gomobile
    - go get golang.org/x/mobile/bind
    - go get -v
    - gomobile bind -target ios -v -prefix Cnb -o lib/Cnlib.framework .
    - zip -r lib/cnlib-ios-$LIBRARY_TAG.zip lib/Cnlib.framework
    - gomobile bind -target android -v -o lib/cnlib-$LIBRARY_TAG.aar .
    - zip -r lib/cnlib-android-$LIBRARY_TAG.zip lib/cnlib-$LIBRARY_TAG-sources.jar lib/cnlib-$LIBRARY_TAG.aar
  after_script:
    - echo "Cleaning up gopath in $PWD"
    - chmod -R u+w gopath
    - rm -Rf gopath

build:branch:
  stage: build
  <<: *build
  variables:
    LIBRARY_TAG: $CI_COMMIT_REF_SLUG
  artifacts:
    paths:
      - lib/cnlib-ios-$CI_COMMIT_REF_SLUG.zip
      - lib/cnlib-android-$CI_COMMIT_REF_SLUG.zip
    expire_in: 2 week
  only:
    - branches@engineering/cnlib
  except:
    - master
    - develop
    - tags

build:latest:
  stage: build
  <<: *build
  variables:
    LIBRARY_TAG: latest
  artifacts:
    paths:
      - lib/cnlib-ios-latest.zip
      - lib/cnlib-android-latest.zip
    expire_in: 30 yrs
  only:
    - develop@engineering/cnlib

build:tagged:
  stage: build
  <<: *build
  variables:
    LIBRARY_TAG: $CI_COMMIT_TAG
  artifacts:
    paths:
      - lib/cnlib-ios-$CI_COMMIT_TAG.zip
      - lib/cnlib-android-$CI_COMMIT_TAG.zip
    expire_in: 30 yrs
  only:
    - tags@engineering/cnlib
  except:
    - branches
